version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    #Décommenter pour pull depuis le dockerhub plutôt que rebuild l'image :
    #image: mullonch/flask_app
    build: ./flask_app
    ports:
      - "8000:8000"
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
