name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint flask_app/app.py
        pylint flask_app/utils.py
        #pylint flask_app/tests/test_functions.py #Erreur d'import à vérifier
        #pylint flask_app/tests/test_integrations.py #Erreur d'import à vérifier
